# Generated by Django 4.0.1 on 2022-01-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_first_name_siteuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
